# Generated by Django 4.0.1 on 2022-03-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=30)),
                ('images', models.ImageField(blank=True, null=True, upload_to='pics/')),
            ],
        ),
    ]
