# Generated by Django 4.0.1 on 2022-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='tools',
            field=models.CharField(default='0', max_length=80),
        ),
    ]
